#!/bin/bash

#for the Raspberry Pi, we need to insert some sort of FILLER here since it cuts off the first bit of audio

string=$@
lang="en-GB"
outfile="/dev/shm/speak.wav"
if [ "$1" == "-l" ] ; then
    lang="$2"
    string=`echo "$string" | sed -r 's/^.{6}//'`
fi

#empty the original file
echo "" > $outfile

#convert string to speech
pico2wave --wave $outfile -l "$lang" "$string"

#play converted speech
play -qV0 $outfile treble 24 gain -l -6 1>>/dev/shm/voice.log 2>>/dev/shm/voice.log
